In [1]:
import webbrowser
from aocd.models import Puzzle
puzzle = Puzzle(year=2020, day=10)
webbrowser.open(puzzle.url);

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
sns.set_style("whitegrid")

## Part 1:

In [164]:
input_data = puzzle.input_data
jolts = np.asarray(list(map(int, input_data.split("\n"))))
jolts.sort()
# add the outlet and the device:
jolts = np.concatenate(([0], jolts, [jolts.max() + 3]))

In [165]:
differences = np.diff(jolts)

In [166]:
answer_a = (differences==1).sum() * (differences==3).sum()
answer_a

2046

In [56]:
puzzle.answer_a = answer_a

That's the right answer!  You are one gold star closer to saving your vacation. [Continue to Part Two]


## Part 2:

In [167]:
jolts

array([  0,   1,   2,   5,   6,   7,   8,   9,  12,  13,  14,  15,  18,
        21,  24,  25,  26,  27,  30,  31,  32,  35,  38,  39,  40,  41,
        44,  47,  50,  51,  52,  53,  54,  57,  58,  59,  60,  61,  64,
        65,  66,  67,  70,  73,  76,  77,  78,  79,  80,  83,  86,  89,
        90,  91,  92,  95,  98, 101, 104, 105, 106, 107, 108, 111, 112,
       113, 114, 115, 118, 119, 120, 121, 122, 125, 126, 129, 132, 133,
       136, 137, 138, 139, 140, 143, 144, 147, 148, 149, 150, 151, 154,
       155, 156, 157, 158, 161])

In [168]:
differences

array([1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 3, 3, 3, 1, 1, 1, 3, 1, 1, 3, 3,
       1, 1, 1, 3, 3, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 3, 3, 3,
       1, 1, 1, 1, 3, 3, 3, 1, 1, 1, 3, 3, 3, 3, 1, 1, 1, 1, 3, 1, 1, 1,
       1, 3, 1, 1, 1, 1, 3, 1, 3, 3, 1, 3, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1,
       1, 3, 1, 1, 1, 1, 3])

In [169]:
def find_sequences_of_ones(values):
    counter = 0
    for v in values:
        if v == 1:
            counter += 1
        else:
            if counter > 0:
                yield counter
            counter = 0
    if counter > 0:
        yield counter

## Some observations:
- Whereever the difference is 3, we definetly need to keep that adapter as well as the one before it
- Therefore we are basically only interested in sequences of ones, we were can choose to skip some of those adapter, but how many?

In [170]:
jolts

array([  0,   1,   2,   5,   6,   7,   8,   9,  12,  13,  14,  15,  18,
        21,  24,  25,  26,  27,  30,  31,  32,  35,  38,  39,  40,  41,
        44,  47,  50,  51,  52,  53,  54,  57,  58,  59,  60,  61,  64,
        65,  66,  67,  70,  73,  76,  77,  78,  79,  80,  83,  86,  89,
        90,  91,  92,  95,  98, 101, 104, 105, 106, 107, 108, 111, 112,
       113, 114, 115, 118, 119, 120, 121, 122, 125, 126, 129, 132, 133,
       136, 137, 138, 139, 140, 143, 144, 147, 148, 149, 150, 151, 154,
       155, 156, 157, 158, 161])

In [171]:
differences

array([1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 3, 3, 3, 1, 1, 1, 3, 1, 1, 3, 3,
       1, 1, 1, 3, 3, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 3, 3, 3,
       1, 1, 1, 1, 3, 3, 3, 1, 1, 1, 3, 3, 3, 3, 1, 1, 1, 1, 3, 1, 1, 1,
       1, 3, 1, 1, 1, 1, 3, 1, 3, 3, 1, 3, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1,
       1, 3, 1, 1, 1, 1, 3])

### Let's try around different options

In [ ]:
# 1 consecutive ones -> 1 options:
5, 6

In [ ]:
# 2 consecutive ones -> 2 options:
4, 5, 6
4, 6

In [ ]:
# 3 consecutive ones -> 3 options
4, 5, 6, 7
4, 6, 7
4, 5, 7
4, 7

In [ ]:
# 4 consecutive ones -> 7 options
4, 5, 6, 7, 8
4, 6, 7, 8
4, 5, 7, 8
4, 5, 6, 8
4, 5, 8
4, 6, 8
4, 7, 8

In [ ]:
# 5 consecutive ones -> 13 options
4, .... 9
4, 5, 6, 7, 8, 9
4, 6, 7, 8, 9  # 5
4, 5, 7, 8, 9  # 6
4, 5, 6, 8, 9  # 7
4, 5, 6, 7, 9  # 8
4, 7, 8, 9  # 5, 6
4, 6, 8, 9  # 5, 7
4, 6, 7, 9  # 5, 8
4, 5, 8, 9  # 6, 7
4, 5, 7, 9  # 6, 8
4, 5, 6, 9  # 7, 8

4, 6, 9  # 5, 7, 8
4, 7, 9  # 5, 6, 8

# don't work:
4, 5, 9
4, 8, 9

## So the combinations follow this series:
- 1, 2, 4, 7, 13
- In the On-Line Encyclopedia of Integer sequences: https://oeis.org/search?q=1%2C2%2C4%2C7%2C13&language=english&go=Search -> Tribonacci numbers

In [179]:
def tribonacci(n):
    if n < 2:
        return 0
    elif n == 2:
        return 1
    return tribonacci(n-1) + tribonacci(n-2) + tribonacci(n-3)

In [192]:
def combinations(consecutive_ones):
    return tribonacci(consecutive_ones + 2)

In [194]:
combinations(4)

7

In [195]:
combinations(5)

13

In [196]:
answer = np.prod([combinations(v) for v in find_sequences_of_ones(differences)])
answer

1157018619904

In [178]:
puzzle.answer_b = answer

That's the right answer!  You are one gold star closer to saving your vacation.You have completed Day 10! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].
